version: 2.7.{build}
configuration: Release
before_build:
- ps: >-
    nuget restore

    if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
       Update-AppveyorBuild -Version "${env:APPVEYOR_BUILD_VERSION}-alpha"
    }
build:
  verbosity: minimal
after_build:
- ps: >-
    nuget pack `
      .\WebApi.Hal\WebApi.Hal.csproj `
      -version $env:APPVEYOR_BUILD_VERSION `
      -outputdirectory .\artifacts `
      -properties "configuration=$env:CONFIGURATION;id=HoneyBear.WebApi.Hal;title=HoneyBear.WebApi.Hal;author=Jake Ginnivan;description=Enabled Hypermedia support in Asp.net Web API using the HAL mediatype"
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
